name: "commit to notion"
author: JoungSik
description: "Write your commit history to notion database."
inputs:
  TOKEN:
    description: "GitHub token"
    required: true
  NOTION_API_KEY:
    description: "Notion API Key"
    required: true
  NOTION_DATABASE:
    description: "Notion Database ID"
    required: true

runs:
  using: node12
  main: dist/index.js

branding:
  icon: "git-commit"
  color: "gray-dark"
